name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '18']

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Verify Node.js version
        run: node --version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Jest
        run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
