name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '18']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        id: node_setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Verify Node.js version
        run: echo "${{ steps.node_setup.outputs.node-version }}"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Jest
        run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build
