name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Verify Node.js version
        run: node --version

      - name: Jest
        run: |
          yarn --frozen-lockfile
          yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build
          run: yarn build
